### ISSUE TITLE
BE: Demo User

### ISSUE THREAD

**Issue by moffatethan** [hatchways/team-cedar#61]
Changes should include the following:

- Add to `sample.env` 
```env
DEMO_USER_EMAIL=
DEMO_USER_PASSWORD=
```
- Create a seeder that creates the demo user account. Name this file `demoSeed.js` and a `seeds` directory.
- In the README, we should update instructions to run the seeder after filling out the demo user details in the `.env` file. 
- Create a route `POST /auth/demo`  that will be nearly identical to the auth code (maybe we can make this a function for maintainability).  
- In the controller for the demo account login, we want to search for the demo user via the email provided in the `DEMO_USER_EMAIL` env variable and create the session (check auth code for how to do this)

**Comment by igor-tanv** [comment]
My understanding of this ticket was to: 

1. Seed (create) a demo user in the db
2. Create way for the demo user to login using the credentials stored in ````.env```` file

The login process for user and demoUser is the same so I reused the ````loginUser```` function in ````controller/auth.js````. 

````loginUser```` now checks for a ````demo```` boolean and if true renders the login credentials from ````process.env````. It was necessary to install ````dotenv```` in order for node to read the env variables. 

PR is ready
